create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password text not null
);

create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password text not null
);

create table if not exists public.complaints (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    title text not null,
    description text not null,
    category text not null,
    location text,
    status text not null default 'Pending',
    image text,
    created_at timestamptz not null default timezone('utc', now())
);

insert into public.admins (name, email, password)
values ('System Admin', 'admin@civictrack.local', 'admin123')
on conflict (email) do nothing;
